### ISSUE TITLE
Need some kind of template engine

### ISSUE THREAD

**Issue by wentwrong** [wentwrong/gh-canary#15]
For dynamic created stuff _(fetched PRs, etc)_ we need some kind of template engine.

**Comment by AndreyBelym** [comment]
Well, for an MVP you can just use functions that return template strings (optionally with dedent module):
```js
const MY_TEMPLATE = ({ title, body }) => dedent `
<html>
  <head><title>${title}</title></head>
  <body>
    ${body}
  </body>
</html>
`;
```

**Comment by AndreyBelym** [comment]
In TestCafe we use Mustache templates for some tasks too.
