### ISSUE TITLE
Github webhooks

### ISSUE THREAD

**Issue by wentwrong** [wentwrong/gh-canary#18]
We might add Github OAuth for safe user authorization _(and webhook creation for repos selected by him)_. Do we need it at this moment?

**Comment by AndreyBelym** [comment]
I think it's not a top priority task. We won't need webhooks if we don't want to receive new PRs in real-time. And we won't user tokens/credentials/etc until we implement functionality that will alter PRs state. For prototyping, we can pass tokens through `.env`. We will decide next, if we will implement full-feautered OAuth login or it will be enough to pass tokens directly.
