### ISSUE TITLE
Replace custom mocking mechanism with `nock` module

### ISSUE THREAD

**Issue by wentwrong** [wentwrong/gh-canary#19]
Currently, mock-data is retrieved manually and for tests we are using two services: one for actual `App` and another for mock github API endpoints. 

Using [Nock](https://github.com/nock/nock) module can be quite useful: 
* fixtures-fetching can be automated;
* no need for additional routing;
* no need for dedicated `App` which host mock third-party API.

Thus, I think that using this module should lead to simplicity of code.

**Comment by AndreyBelym** [comment]
It's a good module and we could use it, but we will have to write E2E tests at some point. While it's possible to use `nock` with TestCafe, it's still not recommended. It's better to use the built-in `RequestMock` or use a standalone mock service.
