### ISSUE TITLE
Add GH authentication

### ISSUE THREAD

**Issue by wentwrong** [wentwrong/gh-canary#20]
Main functionality feature of our application should be **maintainers notification through comments _(user mention)_** on non-collaborator pull requests. For that purpose, at first, we need authenticate our comment-bot on Github.

### My suggestions:
- Authentication by personal access token set via `.env` variables;
- New bot account?

**Comment by AndreyBelym** [comment]
Actually, we already have a bot account - https://github.com/testcafe-build-bot. We can use our personal tokens for development and then switch to `testcafe-build-bot`'s tokens after deploy.
